__data__:
  api:
    authentication:
      method: jwt
      token_expiry: 3600
    endpoints:
      orders: /api/v1/orders
      products: /api/v1/products
      users: /api/v1/users
    rate_limits:
      burst_limit: 50
      requests_per_minute: 1000
  app_name: 默认路径应用
  app_version: 1.1.0
  config_file_path: 
    D:\Tony\Documents\yunpan\invest\invest2025\project\config_manager\src\config\config.yaml
  database:
    credentials:
      password: default_password
      username: admin
    host: db.example.com
    port: 6432
  debug_mode: false
  error_reason: 配置文件中缺少 'required_config' 配置项
  features:
    experimental: false
    new_ui: true
  first_start_time: '2025-06-07T22:13:56.198574'
  logging:
    level: INFO
    path: \var\log\myapp
  missing_config_error: 配置文件中缺少 'titls' 配置项
  scheduler_attempt: started
  scheduler_call_1: using_project_config
  scheduler_call_3: final_call
  scheduler_module: scheduler_started
  scheduler_module_data: from_scheduler
  scheduler_progress: completed
  scheduler_start_time: '2025-06-07T22:14:05.665988'
  scheduler_status: running
  server:
    port: '8080'
    timeout: '30.5'
  task_status: running
  test_async_value: async_test_data
  test_key: test_value
  test_key1: value1
  test_key2: value2
  test_key_new: test_value_new
  version: 1.0.0
__type_hints__:
  logging.path: Path
  server.port: int
  server.timeout: float
