__data__:
  first_start_time: '2025-06-09T19:26:01.430396'
  config_file_path: 
    D:\Tony\Documents\yunpan\invest\invest2025\project\config_manager\debug_path_config.yaml
  project_name: verify_project
  experiment_name: verify_exp
  debug_mode: true
  base_dir: d:\verify_logs
  paths.work_dir: d:\verify_logs\debug\verify_project\verify_exp
  paths.checkpoint_dir: d:\verify_logs\debug\verify_project\verify_exp\checkpoint
  paths.best_checkpoint_dir: d:\verify_logs\debug\verify_project\verify_exp\checkpoint\best
  paths.tsb_logs_dir: d:\verify_logs\debug\verify_project\verify_exp\tsb_logs\2025-06-09\192601
  paths.log_dir: d:\verify_logs\debug\verify_project\verify_exp\logs\2025-06-09\192601
  paths:
    work_dir: d:\verify_logs\debug\verify_project\verify_exp
    checkpoint_dir: d:\verify_logs\debug\verify_project\verify_exp\checkpoint
    best_checkpoint_dir: d:\verify_logs\debug\verify_project\verify_exp\checkpoint\best
    tsb_logs_dir: d:\verify_logs\debug\verify_project\verify_exp\tsb_logs\2025-06-09\192601
    log_dir: d:\verify_logs\debug\verify_project\verify_exp\logs\2025-06-09\192601
__type_hints__: {}
