__data__:
  api:
    authentication:
      method: jwt
      token_expiry: 3600
    endpoints:
      orders: /api/v1/orders
      products: /api/v1/products
      users: /api/v1/users
    rate_limits:
      burst_limit: 50
      requests_per_minute: 1000
  app_name: 默认路径应用
  app_version: 1.1.0
  project_name: config_manager
  # 路径配置模块新增字段
  debug_mode: false
  base_dir: 'd:\demo_logs'
  experiment_name: 'experiment_001'
  paths:
    work_dir: 'd:\demo_logs\config_manager\experiment_001'
    checkpoint_dir: 'd:\demo_logs\config_manager\experiment_001\checkpoint'
    best_checkpoint_dir: 'd:\demo_logs\config_manager\experiment_001\checkpoint\best'
    tsb_logs_dir: 'd:\demo_logs\config_manager\experiment_001\tsb_logs\2025-06-09\220231'
    log_dir: 'd:\demo_logs\config_manager\experiment_001\logs\2025-06-09\220231'
  config_file_path: 
    D:\Tony\Documents\yunpan\invest\invest2025\project\config_manager\src\config\config.yaml
  database:
    credentials:
      password: default_password
      username: admin
    host: db.example.com
    port: 6432
  error_reason: 配置文件中缺少 'required_config' 配置项
  features:
    experimental: false
    new_ui: true
  first_start_time: '2025-06-09T22:02:31.519172'
  logging:
    level: INFO
    path: \var\log\myapp
  missing_config_error: 配置文件中缺少 'titls' 配置项
  scheduler_attempt: started
  scheduler_call_1: using_project_config
  scheduler_call_3: final_call
  scheduler_module: scheduler_started
  scheduler_module_data: from_scheduler
  scheduler_progress: completed
  scheduler_start_time: '2025-06-09T21:41:48.733242'
  scheduler_status: running
  server:
    port: '8080'
    timeout: '30.5'
  task_status: running
  test_async_value: async_test_data
  test_key: test_value
  test_key1: value1
  test_key2: value2
  test_key_new: test_value_new
  version: 1.0.0
  test_backup_isolation: production_value
  paths.work_dir: d:\demo_logs\config_manager\experiment_001
  paths.checkpoint_dir: d:\demo_logs\config_manager\experiment_001\checkpoint
  paths.best_checkpoint_dir: d:\demo_logs\config_manager\experiment_001\checkpoint\best
  paths.tsb_logs_dir: d:\demo_logs\config_manager\experiment_001\tsb_logs\2025-01-07\100000
  paths.log_dir: d:\demo_logs\config_manager\experiment_001\logs\2025-01-07\100000
__type_hints__:
  logging.path: Path
  server.port: int
  server.timeout: float
  # 路径配置模块类型提示
  debug_mode: bool
  base_dir: Path
  project_name: str
  experiment_name: str
  first_start_time: str
  paths.work_dir: Path
  paths.checkpoint_dir: Path
  paths.best_checkpoint_dir: Path
  paths.tsb_logs_dir: Path
  paths.log_dir: Path
