__data__:
  project_name: test_project
  first_start_time: '2025-07-02T19:15:41.140293'
  test_mode: true
  concurrency: 5
  timeout: 30
  proxy:
    http: http://localhost:3213
    https: https://localhost:3214
    url: http://proxy.example.com:8080
  headers:
    Accept: text/html,application/xhtml+xml
    Content_Type: application/json
  url_validation:
    level2_pattern: ^https?://[^/]+/chapter/\d+$
    exclude_image_patterns:
      - \.jpg$
      - \.png$
      - \.gif$
  base_dir: ./data
  work_dir: ./data/work
  log_dir: ./data/logs
  config_file_path: 
    /mnt/ntfs_data/ubuntu_data/NutstoreFiles/invest2025/project/config_manager/src/config/config.yaml
  experiment_name: experiment_name
  paths:
    work_dir: data/test_project/experiment_name
    checkpoint_dir: data/test_project/experiment_name/checkpoint
    best_checkpoint_dir: data/test_project/experiment_name/checkpoint/best
    debug_dir: data/test_project/experiment_name/debug
    tensorboard_dir: data/test_project/experiment_name/tensorboard
    tsb_logs_dir: data/test_project/experiment_name/tsb_logs/2025-07-02/191541
    log_dir: data/test_project/experiment_name/logs/2025-07-02/191541
  missing_config_error: 配置文件中缺少 'titls' 配置项
  test_async_value: async_test_data
  scheduler_status: running
  scheduler_start_time: '2025-07-02T19:00:04.454147'
  scheduler_progress: completed
__type_hints__: {}
