__data__:
  project_name: test_project
  first_start_time: '2025-01-07T18:15:20'
  test_mode: true
  concurrency: 5
  timeout: 30
  proxy:
    http: http://localhost:3213
    https: https://localhost:3214
    url: http://proxy.example.com:8080
  headers:
    Accept: text/html,application/xhtml+xml
    Content_Type: application/json
  url_validation:
    level2_pattern: ^https?://[^/]+/chapter/\d+$
    exclude_image_patterns:
      - \.jpg$
      - \.png$
      - \.gif$
  base_dir: /tmp/original/base/path
  work_dir: /tmp/original/work/path
  log_dir: /tmp/original/log/path
  config_file_path: 
    /mnt/ntfs_data/ubuntu_data/NutstoreFiles/invest2025/project/config_manager/src/config/config.yaml
__type_hints__: {}
