__data__:
  first_start_time: '2025-06-09T19:22:59.079929'
  config_file_path: 
    D:\Tony\Documents\yunpan\invest\invest2025\project\config_manager\temp_config_2.yaml
  base_dir: d:\ml_experiments
  project_name: ml_research
  experiment_name: bert_fine_tuning
  debug_mode: false
  paths.work_dir: d:\ml_experiments\ml_research\bert_fine_tuning
  paths:
    work_dir: d:\ml_experiments\ml_research\bert_fine_tuning
    checkpoint_dir: d:\ml_experiments\ml_research\bert_fine_tuning\checkpoint
    best_checkpoint_dir: d:\ml_experiments\ml_research\bert_fine_tuning\checkpoint\best
    tsb_logs_dir: d:\ml_experiments\ml_research\bert_fine_tuning\tsb_logs\2025-06-09\192259
    log_dir: d:\ml_experiments\ml_research\bert_fine_tuning\logs\2025-06-09\192259
  paths.checkpoint_dir: d:\ml_experiments\ml_research\bert_fine_tuning\checkpoint
  paths.best_checkpoint_dir: d:\ml_experiments\ml_research\bert_fine_tuning\checkpoint\best
  paths.tsb_logs_dir: d:\ml_experiments\ml_research\bert_fine_tuning\tsb_logs\2025-06-09\192259
  paths.log_dir: d:\ml_experiments\ml_research\bert_fine_tuning\logs\2025-06-09\192259
__type_hints__: {}
