__data__:
  project_name: test_project
  first_start_time: '2025-01-07T18:15:20'
  test_mode: true
  concurrency: 5
  timeout: 30
  proxy:
    http: http://localhost:3213
    https: https://localhost:3214
    url: http://proxy.example.com:8080
  headers:
    Accept: text/html,application/xhtml+xml
    Content_Type: application/json
  url_validation:
    level2_pattern: ^https?://[^/]+/chapter/\d+$
    exclude_image_patterns:
      - \.jpg$
      - \.png$
      - \.gif$
  base_dir:
    windows: D:\logs
    ubuntu: ~/logs
  experiment_name: experiment_name
  missing_config_error: 配置文件中缺少 'titls' 配置项
  test_async_value: async_test_data
  scheduler_status: running
  scheduler_start_time: '2025-07-03T18:34:06.033152'
  scheduler_progress: completed
__type_hints__: {}
