__data__:
  project_name: config_manager
  first_start_time: '2025-01-07T10:00:00'
  test_mode: false
  base_dir:
    linux: /tony/home/logs
    windows: d:/logs
  experiment_name: experiment_name
__type_hints__:
  first_start_time: datetime.datetime