__data__:
  project_name: config_manager
  first_start_time: '2025-01-07T10:00:00'

  test_mode: false
  base_dir:
    linux: /tony/home/logs
    windows: d:/logs
  experiment_name: experiment_name
  config_file_path:
    /mnt/ntfs/ubuntu_data/NutstoreFiles/invest2025/project/config_manager/src/config/config.yaml
  paths:
    work_dir: /tony/home/logs/config_manager/experiment_name
    checkpoint_dir: /tony/home/logs/config_manager/experiment_name/checkpoint
    best_checkpoint_dir: /tony/home/logs/config_manager/experiment_name/checkpoint/best
    debug_dir: /tony/home/logs/config_manager/experiment_name/debug
    tensorboard_dir: /tony/home/logs/config_manager/experiment_name/tensorboard
    tsb_logs_dir: /tony/home/logs/config_manager/experiment_name/tsb_logs/2025/02/01/07/100000
    log_dir: /tony/home/logs/config_manager/experiment_name/logs/20250107/100000
    backup_dir: /tony/home/logs/config_manager/experiment_name/backup/20250107/100000
  test_backup_isolation: production_value
__type_hints__:
  first_start_time: datetime
