__data__:
  project_name: test_project
  first_start_time: '2025-01-07T18:15:20'
  test_mode: true
  base_dir: /tmp/original/base/path
  experiment_name: experiment_name
  config_file_path: 
    /mnt/ntfs/ubuntu_data/NutstoreFiles/invest2025/project/config_manager/src/config/config.yaml
  paths:
    work_dir: /tmp/original/base/path/test_project/experiment_name
    log_dir: /tmp/original/base/path/test_project/experiment_name/logs/20250107/181520
    data_dir: /tmp/default/data
    checkpoint_dir: /tmp/original/base/path/test_project/experiment_name/checkpoint
    best_checkpoint_dir: /tmp/original/base/path/test_project/experiment_name/checkpoint/best
    debug_dir: /tmp/original/base/path/test_project/experiment_name/debug/20250107/181520
    tensorboard_dir: 
      /tmp/original/base/path/test_project/experiment_name/tensorboard/2025/02/01/07/181520
    tsb_logs_dir: 
      /tmp/original/base/path/test_project/experiment_name/tsb_logs/2025/02/01/07/181520
    backup_dir: /tmp/original/base/path/test_project/experiment_name/backup/20250107/181520
    cache_dir: /tmp/original/base/path/test_project/experiment_name/cache
  concurrency: 5
  timeout: 30
  proxy:
    http: http://localhost:3213
    https: https://localhost:3214
    url: http://proxy.example.com:8080
  headers:
    Accept: text/html,application/xhtml+xml
    Content_Type: application/json
  url_validation:
    level2_pattern: ^https?://[^/]+/chapter/\d+$
    exclude_image_patterns:
      - \.jpg$
      - \.png$
      - \.gif$
  work_dir: /tmp/original/work/path
  log_dir: /tmp/original/log/path
__type_hints__:
  first_start_time: datetime
