__data__:
  project_name: project_name
  first_start_time: '2025-01-07T18:15:20'
  test_mode: true
  concurrency: 5
  timeout: 30
  proxy:
    http: http://localhost:3213
    https: https://localhost:3214
    url: http://proxy.example.com:8080
  headers:
    Accept: text/html,application/xhtml+xml
    Content_Type: application/json
  url_validation:
    level2_pattern: ^https?://[^/]+/chapter/\d+$
    exclude_image_patterns:
      - \.jpg$
      - \.png$
      - \.gif$
  base_dir: /tmp/original/base/path
  work_dir: /tmp/original/work/path
  log_dir: /tmp/original/log/path
  config_file_path: 
    /mnt/ntfs/ubuntu_data/NutstoreFiles/invest2025/project/config_manager/src/config/config.yaml
  experiment_name: experiment_name
  paths:
    checkpoint_dir: /tmp/original/base/path/project_name/experiment_name/checkpoint
    best_checkpoint_dir: /tmp/original/base/path/project_name/experiment_name/checkpoint/best
    debug_dir: /tmp/original/base/path/project_name/experiment_name/debug
    tensorboard_dir: /tmp/original/base/path/project_name/experiment_name/tensorboard
    tsb_logs_dir: 
      /tmp/original/base/path/project_name/experiment_name/tsb_logs/2025/02/01/07/181520
    backup_dir: /tmp/original/base/path/project_name/experiment_name/backup/20250107/181520
    work_dir: /tmp/original/base/path/project_name/experiment_name
    log_dir: /tmp/original/base/path/project_name/experiment_name/logs/20250107/181520
  missing_config_error: 配置文件中缺少 'titls' 配置项
  test_async_value: async_test_data
  scheduler_status: running
  scheduler_start_time: '2025-07-20T14:21:14.036611'
  scheduler_progress: completed
  __type_hints__:
    first_start_time: datetime
  test_backup_isolation: production_value
__type_hints__: {}
