__data__:
  first_start_time: '2025-06-09T19:41:43.730389'
  config_file_path: 
    D:\Tony\Documents\yunpan\invest\invest2025\project\config_manager\detailed_debug_config.yaml
  base_dir: d:\config_test
  project_name: config_project
  experiment_name: config_exp
  debug_mode: true
  paths.work_dir: d:\config_test\debug\config_project\config_exp
  paths.checkpoint_dir: d:\config_test\debug\config_project\config_exp\checkpoint
  paths.best_checkpoint_dir: d:\config_test\debug\config_project\config_exp\checkpoint\best
  paths.tsb_logs_dir: d:\config_test\debug\config_project\config_exp\tsb_logs\2025-06-09\194143
  paths.log_dir: d:\config_test\debug\config_project\config_exp\logs\2025-06-09\194143
  paths:
    work_dir: d:\config_test\debug\config_project\config_exp
    checkpoint_dir: d:\config_test\debug\config_project\config_exp\checkpoint
    best_checkpoint_dir: d:\config_test\debug\config_project\config_exp\checkpoint\best
    tsb_logs_dir: d:\config_test\debug\config_project\config_exp\tsb_logs\2025-06-09\194143
    log_dir: d:\config_test\debug\config_project\config_exp\logs\2025-06-09\194143
__type_hints__: {}
